### ISSUE TITLE
Regarding PRs

### ISSUE THREAD

**Issue by AsliRoy** [AB1908/CS-Books#5]
So, whenever you are going to accept contributions, I guess, you need people to branch out the name of the course they are interested to write about. The branch name should ideally be /name1-name2-.., for e.g. /theory-of-computation . 
Any ideas/suggestions about the format of the text? So that I can incorporate the template in contributing.md ?

**Comment by AB1908** [comment]
For the topic you wish to contribute, simply name it as topic-name-like-this. Example: `operating-systems`. Apart from that, if you wish to contribute to an existing topic or branch, simply open an issue referencing it.

**Comment by AB1908** [comment]
For an entire topic, I have made a sample template.

```
## Topic Heading Here

### Standard Textbooks

1. **Book1** - Author1 <sup>[1](#dsa1)</sup>
2. **Book2** - Author2 [2]

### Alternative/Supplementary

1. **Book1** - Author1
2. **Book2** - Author2 [3]

### Notes

<sup id="dsa1">1</sup> - Used as reference for

- [CSxxx at UXX](course-hyperlink)
- [CSxxx at UXX](course-hyperlink)

[2] - Used as reference for

- [CSxxx at UXX](course-hyperlink)
- [CSxxx at UXX](course-hyperlink)

[3] - Used as reference for [CSyyy at UXYZ](course-hyperlink) where some famous instructor teaches.

# References

- NITR Curricula (because that's what I'm basing this off of)
- [XYZ Curricula at XYZ University](hyperlink-to-curricula-if-available)

## Websites

   [some-wikipedia-page](with-wikipedia-link-here)  
   [some-other-page](with-link-here)  

## Courses

- Topic-name

  [CSXXX - Full-univ-name-here](hyperlink-to-course)  
  [CSXXX - Full-univ-name-here](hyperlink-to-course)  
  [CSXXX - Full-univ-name-here](hyperlink-to-course)  

## Resources

- [awesome-resource](awesome-link)

# Miscellaneous Links

- Uncategorized reference

```
`'` indicates a space. Three leading spaces and two trailing spaces allow you to have paragraphs without line breaks as in Courses under References. Keep in mind that the references section already exists! No need to create another one. We'll have one reference section to rule them all, as suggested below by @AsliRoy.

Found a great link but couldn't categorize it? Keep it in miscellaneous for now. In case there isn't a miscellaneous section, go ahead and create a header for it at the end and add all you want.

It comes out looking like 

## Topic Heading Here

### Standard Textbooks

1. **Book1** - Author1 [^1]
2. **Book2** - Author2 [2]

### Alternative/Supplementary

1. **Book1** - Author1
2. **Book2** - Author2 [3]

### Notes

[^1]: Used as reference for

- [CSxxx at UXX](course-hyperlink)
- [CSxxx at UXX](course-hyperlink)

[2] - Used as reference for

- [CSxxx at UXX](course-hyperlink)
- [CSxxx at UXX](course-hyperlink)

[3] - Used as reference for [CSyyy at UXYZ](course-hyperlink) where some famous instructor teaches.

# References

- NITR Curricula (because that's what I'm basing this off of)
- [XYZ Curricula at XYZ University](hyperlink-to-curricula-if-available)

## Websites

   [some-wikipedia-page](with-wikipedia-link-here)  
   [some-other-page](with-link-here)  

## Courses

- Topic-name

  [CSXXX - Full-univ-name-here](hyperlink-to-course)  
  [CSXXX - Full-univ-name-here](hyperlink-to-course)  
  [CSXXX - Full-univ-name-here](hyperlink-to-course)  

## Resources

- [awesome-resource](awesome-link)

# Miscellaneous Links

- Uncategorized reference

**Comment by AB1908** [comment]
Improvements to the template above are very welcome as changes further down the line will be more time intensive than now. Once a satisfactory template has been achieved, there will be no further template changes until a v1 of the curriculum books is complete and ready for use.

**Comment by AsliRoy** [comment]
I like the template, but don't you think the course names, in the references feel a bit repetitive? Since we are already using them above. I am pretty sure there must be a better way to go about it. 
One way to go about it, would be to have a universal set _only_ of these courses. That way, multiple subjects ca reference back to them, still avoid redundancy. 
Case in point: For someone who wants to learn Compiler Design, he still has to get through Theory of Computation and Automata Theory. So under the  used as a reference for section, we can write the name of TOC course, and link it to a universal list of courses. Which will be the same link given to someone who searches in the TOC curriculum section. Suggestions?

**Comment by AB1908** [comment]
The idea is one I have previously thought of, but not seriously. The concept seems much better, so I'll make modifications to the template.

**Comment by AB1908** [comment]
One way to go about it is to categorize the courses by University. That way, all links (with their relevant descriptions) will be categorised.

**Comment by AB1908** [comment]
Also, would like to point out that though your idea of prerequisites is absolutely necessary, it's not one that furthers our progress towards a list of books. The idea will definitely be kept in mind for future implementation.

**Comment by AB1908** [comment]
Relevant changes have been made starting from the MP & MC branch, and are now reflected in `dev` branch after merging. Updates to the template will be made soon.

Edit: PR Template Updated!

**Comment by AsliRoy** [comment]
@AB1908 , I think the work is coming on nicely now. Should I commit the contributing.md PR template to the dev branch? Or should we wait for some time?

**Comment by AB1908** [comment]
Create a pull request and I'll review ASAP!

**Comment by AB1908** [comment]
PR #12 addresses this issue for now. Closed until further notice.

**Comment by AB1908** [comment]
A contributing.md file has been created, and PR Template has moved to it's own file as per community guidlines.
